### ISSUE TITLE
How the Download URL in Markdown Syntax must be called

### ISSUE THREAD

**Issue by ghost** [james2doyle/pico_download#3]
Hello Developers,

I'm just making my first experiences with this plugin and is not quite clear. How the download URL in Markdown syntax must be called.

In the directory `/content/download/de_de.zip` I have a ZIP file.

How should I download the download URL, which I have to insert in the page downloads.md.

Thanks in advance.

**Comment by james2doyle** [comment]
I am no longer supporting this plugin as pico has changed and I don't believe this plugin still works
